"use client";

import { useState } from "react";
import { CheckCircle2 } from "lucide-react";
import { clientServices } from "@/data/client-content";

export default function BookingForm() {
  const [submitted, setSubmitted] = useState(false);

  if (submitted) return <div className="rounded-2xl border border-brand-gold/60 bg-brand-ivory p-8 text-center shadow-sm"><CheckCircle2 className="mx-auto h-10 w-10 text-emerald-600" /><h3 className="mt-4 font-serif text-2xl text-brand-burgundy">Request received</h3><p className="mt-2 text-sm text-brand-charcoal/70">Our concierge will confirm your appointment shortly.</p><button type="button" onClick={() => setSubmitted(false)} className="mt-5 text-sm font-semibold text-brand-rose hover:text-brand-burgundy">Make another request</button></div>;

  return <form onSubmit={(event) => { event.preventDefault(); setSubmitted(true); }} className="grid gap-4 rounded-2xl border border-brand-blush/60 bg-brand-ivory p-6 shadow-sm sm:grid-cols-2 sm:p-8"><div><label htmlFor="booking-name" className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-brand-rose">Your name</label><input id="booking-name" required className="h-11 w-full rounded-xl border border-brand-blush bg-brand-ivory px-4 text-sm outline-none focus:border-brand-rose focus:ring-2 focus:ring-brand-rose/20" /></div><div><label htmlFor="booking-email" className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-brand-rose">Email</label><input id="booking-email" type="email" required className="h-11 w-full rounded-xl border border-brand-blush bg-brand-ivory px-4 text-sm outline-none focus:border-brand-rose focus:ring-2 focus:ring-brand-rose/20" /></div><div><label htmlFor="booking-service" className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-brand-rose">Treatment</label><select id="booking-service" required defaultValue="" className="h-11 w-full rounded-xl border border-brand-blush bg-brand-ivory px-4 text-sm outline-none focus:border-brand-rose"><option value="" disabled>Select a treatment</option>{clientServices.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select></div><div><label htmlFor="booking-date" className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-brand-rose">Preferred date</label><input id="booking-date" type="date" required className="h-11 w-full rounded-xl border border-brand-blush bg-brand-ivory px-4 text-sm outline-none focus:border-brand-rose" /></div><div className="sm:col-span-2"><label htmlFor="booking-note" className="mb-1.5 block text-xs font-semibold uppercase tracking-wider text-brand-rose">Anything we should know?</label><textarea id="booking-note" rows={3} className="w-full rounded-xl border border-brand-blush bg-brand-ivory p-4 text-sm outline-none focus:border-brand-rose" /></div><button type="submit" className="sm:col-span-2 inline-flex h-12 items-center justify-center rounded-xl bg-brand-burgundy px-6 text-sm font-semibold text-white transition-colors hover:bg-brand-rose">Request appointment</button></form>;
}
